services:
  # Backend API
  - type: web
    name: immo-albania-backend
    env: node
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run migrate && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: immo-albania-db
          property: externalConnectionString

  # Frontend
  - type: web
    name: immo-albania-frontend
    env: node
    plan: free
    region: frankfurt
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_HOST
        fromService:
          name: immo-albania-backend
          type: web
          property: host
      - key: NEXT_PUBLIC_BACKEND_HOST
        fromService:
          name: immo-albania-backend
          type: web
          property: host
      - key: NEXT_PUBLIC_APP_URL
        value: https://immo-albania-frontend.onrender.com

databases:
  - name: immo-albania-db
    plan: free
    region: frankfurt
    databaseName: immo_albania
    user: immo_user
